network:
    version: 2
    ethernets:
        enp3s0:                               # Private network interface
            renderer: networkd
            optional: true
            dhcp4: true
            dhcp4-overrides:
                use-routes: false
                # route-metric: 3
                # networkd
                use-dns: true                 # @todo resolv.conf
                use-hostname: false
