network:
    version: 2
    ethernets:
        enp3s0:                               # Private network interface
            renderer: networkd
            dhcp4: yes
            dhcp4-overrides:
                use-routes: false
                route-metric: 3
                # networkd
                use-dns: true
                use-hostname: false
